name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cmake-version: [3.12]
        compiler: [clang-9]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libusb-1.0-0-dev
    - name: Set version
      id: set_version
      run: echo ::set-output name=version::${{ github.sha }}
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DVERSION=${{ steps.set_version.outputs.version }} ..
        make
    - name: Create Release Draft
      id: create_release_draft
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set_version.outputs.version }}
        release_name: Release ${{ steps.set_version.outputs.version }}
        draft: true
        prerelease: false

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: autoconf automake libtool pkg-config make gcc cmake
    - name: Set version
      id: set_version
      run: echo ::set-output name=version::${{ github.sha }}
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DVERSION=${{ steps.set_version.outputs.version }} .. -G "MinGW Makefiles"
        mingw32-make
    - name: Create Release Draft
      id: create_release_draft
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set_version.outputs.version }}
        release_name: Release ${{ steps.set_version.outputs.version }}
        draft: true
        prerelease: false
